Vagrant.configure(2) do |config|
  config.vm.box = 'dduportal/boot2docker'
  jenkins_host_port =
    ENV['jenkins_host_port'] ? ENV['jenkins_host_port'].to_i : 8080
  config.vm.network :forwarded_port, guest: 8080, host: jenkins_host_port

  if ENV['http_proxy'] && Vagrant.has_plugin?('vagrant-proxyconf')
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['https_proxy']
    config.proxy.no_proxy = ENV['no_proxy']
  end
end
